### ISSUE TITLE
Divers petits bugs

### ISSUE THREAD

**Issue by SckyzO** [matthiasbosc/t412#10]
Bonjour, 

Suite à mon précédent report, j'ai regardé un peu mes fichiers .error d'apache

Je remonte quelques "petits" soucis, dont un concernant la sécurité des mots de passe. 

Voici un copier/coller de mes logs (je masque juste les informations confidentielles)
```
[Mon Jan 23 17:56:09.871468 2017] [core:info] [pid 10483] [client xx.xx.xx.xx:55254] AH00128: File does not exist: /var/www/html/t412/img/pinlayer2.png"), url("http:/monserveur.fr/t412/img/pinlayer1.png"), url("http:/monserveur.fr/t412/img/back.png, referer: http://monserveur.fr/t412/login.php
[Mon Jan 23 17:56:10.450751 2017] [core:info] [pid 10483] [client xx.xx.xx.xx:55254] AH00128: File does not exist: /var/www/html/favicon.ico
[Mon Jan 23 17:56:10.766972 2017] [core:info] [pid 10483] [client xx.xx.xx.xx:55254] AH00128: File does not exist: /var/www/html/favicon.ico
[Mon Jan 23 17:56:14.805148 2017] [core:info] [pid 10483] [client xx.xx.xx.xx:55254] AH00128: File does not exist: /var/www/html/t412/img/pinlayer2.png"), url("http:/monserveur.fr/t412/img/pinlayer1.png"), url("http:/monserveur.fr/t412/img/back.png, referer: http://monserveur.fr/t412/login.php

[Mon Jan 23 17:56:23.864155 2017] [:error] [pid 10781] [client xx.xx.xx.xx:55272] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)' in /var/www/html/t412/user.class.php:10\nStack trace:\n#0 /var/www/html/t412/user.class.php(10): PDO->__construct('mysql:host=loca...', 'LOGIN_MYSQL', 'MOT_DE_PASSE_EN_CLAIR')\n#1 /var/www/html/monserveur.fr/t412/user.class.php(39): User->connect()\n#2 /var/www/html/t412/torrent.class.php(59): User->storeCredentials('94312552', '\\x1EM\\x0F&\\xC2\\xC6\\xBD\\x04cZH )\\x8A\\xB6...', '\\x06\\x97\\xD5\\x88i\\x95+\\x96\\xA9\\xD6\\xF9\\x9F\\x86\\xA7\\\\...')\n#3 /var/www/html/t412/login.php(7): Torrent->Auth('MON_USER_ID', 'MOT_DE_PASSE_EN_CLAIR', 1492966583)\n#4 {main}\n  thrown in /var/www/html/t412/user.class.php on line 10, referer: http://monserveur.fr/t412/login.php

[Mon Jan 23 17:56:25.445813 2017] [core:info] [pid 10484] [client 207.241.226.216:51893] AH00128: File does not exist: /var/www/html/robots.txt

[Mon Jan 23 17:56:36.039064 2017] [core:info] [pid 10483] [client xx.xx.xx.xx:55276] AH00128: File does not exist: /var/www/html/t412/img/pinlayer2.png"), url("http:/monserveur.fr/t412/img/pinlayer1.png"), url("http:/monserveur.fr/t412/img/back.png, referer: http://monserveur.fr/t412/login.php

[Mon Jan 23 17:56:48.730168 2017] [:error] [pid 10781] [client 7xx.xx.xx.xx:55278] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)' in /var/www/html/t412/user.class.php:10\nStack trace:\n#0 /var/www/html/t412/user.class.php(10): PDO->__construct('mysql:host=loca...', 'LOGIN_MYSQL', 'MOT_DE_PASSE_EN_CLAIR')\n#1 /var/www/html/monserveur.fr/t412/user.class.php(39): User->connect()\n#2 /var/www/html/t412/torrent.class.php(59): User->storeCredentials('94312552', '\\xE0\\v]L\\xDE\\xDE\\x93\\x1CKJSR\\x1E\\xB0%...', 'R\\x9Ex\\xB6\\xD0RedC\\xE3v\\x9F.\\xB1<...')\n#3 /var/www/html/t412/login.php(7): Torrent->Auth('MON_USER_ID', 'MOT_DE_PASSE_EN_CLAIR', 1492966605)\n#4 {main}\n  thrown in /var/www/html/t412/user.class.php on line 10, referer: http://monserveur.fr/t412/login.php

[Mon Jan 23 17:56:55.330502 2017] [core:info] [pid 10483] [client xx.xx.xx.xx:55292] AH00128: File does not exist: /var/www/html/t412/img/pinlayer2.png"), url("http:/monserveur.fr/t412/img/pinlayer1.png"), url("http:/monserveur.fr/t412/img/back.png, referer: http://monserveur.fr/t412/login.php

[Mon Jan 23 17:57:03.884194 2017] [core:info] [pid 10484] [client xx.xx.xx.xx:55296] AH00128: File does not exist: /var/www/html/t412/img/pinlayer2.png"), url("http:/monserveur.fr/t412/img/pinlayer1.png"), url("http:/monserveur.fr/t412/img/back.png, referer: http://monserveur.fr/t412/login.php

[Mon Jan 23 17:57:26.176694 2017] [:error] [pid 10483] [client xx.xx.xx.xx:55318] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)' in /var/www/html/t412/user.class.php:10\nStack trace:\n#0 /var/www/html/t412/user.class.php(10): PDO->__construct('mysql:host=loca...', 'LOGIN_MYSQL', 'MOT_DE_PASSE_EN_CLAIR')\n#1 /var/www/html/monserveur.fr/t412/user.class.php(39): User->connect()\n#2 /var/www/html/t412/torrent.class.php(59): User->storeCredentials('94312552', '\\xE8\\x98\\x0Fl\\x8F\\xF1C4\\xEF\\xBE A\\xB4\\xE3>...', '\\xF9\\xC8\\x82\\x801\\xE24\\xE02{\\x07w\\x1C\\xFFE...')\n#3 /var/www/html/t412/login.php(7): Torrent->Auth('MON_USER_ID', 'MOT_DE_PASSE_EN_CLAIR', 1492966645)\n#4 {main}\n  thrown in /var/www/html/t412/user.class.php on line 10, referer: http://monserveur.fr/t412/login.php

[Mon Jan 23 17:58:27.762827 2017] [core:info] [pid 16028] [client xx.xx.xx.xx:55326] AH00128: File does not exist: /var/www/html/t412/img/pinlayer2.png"), url("http:/monserveur.fr/t412/img/pinlayer1.png"), url("http:/monserveur.fr/t412/img/back.png, referer: http://monserveur.fr/t412/login.php
```

Le premier point est que parfois j'ai des URL mal formée : 
```
[Mon Jan 23 17:58:27.762827 2017] [core:info] [pid 16028] [client xx.xx.xx.xx:55326] AH00128: File does not exist: /var/www/html/t412/img/pinlayer2.png"), url("http:/monserveur.fr/t412/img
```
Ici on peut voir qu'il me génère l'URL http:/monserveur (il manque un /)
Je n'ai pas trouvé dans le code encore l'erreur ...

Second point : J'avais mon serveur MySQL planté, pas de soucis, mais en regardant les logs, j'ai vu que les logs ecrivent en clair les mots de passe mysql_connect et aussi le login t411 ... Mais uniquement quand la BDD n'arrive pas a se connecter. 
Serait-il possible de "crypter" ou d'enlever les références des logins/mot de passe ? c'est dangeureux
Pour reproduire l'erreur j'ai juste stoppé la DBB mysql et regardé mon log error d'apache

Login MYSQL et T411
```
[Mon Jan 23 17:56:23.864155 2017] [:error] [pid 10781] [client xx.xx.xx.xx:55272] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)' in /var/www/html/t412/user.class.php:10\nStack trace:\n#0 /var/www/html/t412/user.class.php(10): PDO->__construct('mysql:host=loca...', 'LOGIN_MYSQL', 'MOT_DE_PASSE_EN_CLAIR')\n#1 /var/www/html/monserveur.fr/t412/user.class.php(39): User->connect()\n#2 /var/www/html/t412/torrent.class.php(59): User->storeCredentials('94312552', '\\x1EM\\x0F&\\xC2\\xC6\\xBD\\x04cZH )\\x8A\\xB6...', '\\x06\\x97\\xD5\\x88i\\x95+\\x96\\xA9\\xD6\\xF9\\x9F\\x86\\xA7\\\\...')\n#3 /var/www/html/t412/login.php(7): Torrent->Auth('MON_USER_ID', 'MOT_DE_PASSE_EN_CLAIR', 1492966583)\n#4 {main}\n  thrown in /var/www/html/t412/user.class.php on line 10, referer: http://monserveur.fr/t412/login.php
```

Troisième point/bug, 
Lorsque je clic sur Déconnexion mais que je fais retour en arrière, je suis toujours connecté, même si je ferme l'onglet et que je le réouvre la connexion est toujours persistante. 
Le lien pour la déco ne renvoit que sur /login.php en fait et en déconnecte pas la session en cours.

En espérant t'aider :)

Cordialement

**Comment by matthiasbosc** [comment]
Peux-tu me préciser ton environnement (OS, serveur web, version de php et méthode d’exécution) ?
Je n'arrive pas à reproduire le bug..

**Comment by SckyzO** [comment]
Alors pour l'OS c'est Debian 8
██ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 8.7 (jessie)
Release:	8
Codename:	jessie

Pour php 
██ php -v
PHP 5.6.30-0+deb8u1 (cli) (built: Feb  8 2017 08:50:21) 

Méthode d'exécution ? 
Et bien pour le mot de passe en clair dans les logs : 
Tu démarres ton serveur apache, ton mysql, ton serveur web.
Tu te connectes sur t412 (ou pas ?)
Puis tu kill ton mysql (proprement ou pas)
Ensuite tu regardes les logs (	LogLevel info )
Et tu verras ton mot de passe t412 en clair.
